version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: expense_tracker_api_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/expense_tracker_api_dev
      SECRET_KEY_BASE: your-secret-key-base-here-change-this-in-production
      PHX_HOST: localhost
      PORT: 4000
    volumes:
      - ./expense_tracker_api:/app
    command: sh -c "mix ecto.setup && mix phx.server"

volumes:
  postgres_data: